### ISSUE TITLE
irc.bot is not capable of SSL

### ISSUE THREAD

**Issue by dataCobra** [bastienboutonnet/datafrittata-twitch-chatbot#17]
Hey @bastienboutonnet,

yesterday I've tested a bit with the bot and found out that there is currently no way to get a SSL connection working.
I think there is no good reason to not use SSL.

Do you mind if I rework the IRC functionality? I would use `socket` and `ssl` to make it work. This are also 2 builtin modules and
this means that we can get rid of some dependencies.

Regards,
Ben

**Comment by bastienboutonnet** [comment]
Hey @dataCobra 

Great point! 

I would say yes I wouldn't mind at all. That being said, I plan to work on turning the bot into an async one. This means that potentially all your hard work may go down the train as using asyncio will make use of stream handlers etc.

That was the reason why I was basically using that module as a quick shortcut until I actually start focusing on the async stuff. I want to make it async for a variety of reasons:
- some commands (will) take time and we don't want to miss messages or have collisions
- I want to learn asyncio and this is a good excuse
- I would like to knock off the dependency on irc bot and have my own one where I can enforce a different structure and parsing of the event data.

So... It depends, if you want to have a go at it because you find it fun and would not be sad if some of the things you build may become deprecated soon then go ahead if not, we'll get to it on stream or off stream at some point.

**Comment by dataCobra** [comment]
If it's a quick shortcut and you want to implement it with async in the future, I don't see a reason for me to work on it now. :+1:

I'll wait till you work on that and then I can learn about async with you. :slightly_smiling_face:

**Comment by bastienboutonnet** [comment]
Sounds good to me. I think I want to do a few more sessions on "fun" features, and then I'll go over refactoring things to work entirely async and scrapping irc.bot entirely. So yeah it makes sense I think
